// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/gamma/events/get.js";

const args = {
  id: argument.string().required().describe("Event ID or slug"),
} as const;

const options = {
  bySlug: option.boolean().short("s").describe("Lookup by slug instead of ID"),
} as const;

export const getCommand = defineCommand({
  name: "get",
  description: "Get a specific event by ID or slug",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type GetArgs = InferArgs<typeof args>;
export type GetOptions = InferOptions<typeof options>;
