// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/events/list.js";

const options = {
  offset: option.number().describe("Pagination offset (default: 0)"),
  active: option.boolean().short("a").describe("Filter active events"),
  limit: option.number().describe("Maximum number of results (default: 10)"),
  tagId: option.string().describe("Filter by tag ID"),
  ascending: option.boolean().describe("Sort ascending (default: true)"),
  closed: option.boolean().short("c").describe("Filter closed events"),
} as const;

export const listCommand = defineCommand({
  name: "list",
  description: "List events with filtering",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListOptions = InferOptions<typeof options>;
