// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { buildersCommand } from "./data/builders.js";
import { holdersCommand } from "./data/holders.js";
import { liveVolumeCommand } from "./data/live-volume.js";
import { openInterestCommand } from "./data/open-interest.js";
import { usersCommand } from "./data/users.js";

export const dataCommand = defineCommand({
  name: "data",
  description: "Polymarket Data API commands",
  subcommands: {
    builders: buildersCommand,
    openInterest: openInterestCommand,
    liveVolume: liveVolumeCommand,
    users: usersCommand,
    holders: holdersCommand,
  },
});
