// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { commentsCommand } from "./gamma/comments.js";
import { eventsCommand } from "./gamma/events.js";
import { marketsCommand } from "./gamma/markets.js";
import { seriesCommand } from "./gamma/series.js";
import { sportsCommand } from "./gamma/sports.js";
import { tagsCommand } from "./gamma/tags.js";

export const gammaCommand = defineCommand({
  name: "gamma",
  description: "Polymarket Gamma API commands",
  subcommands: {
    comments: commentsCommand,
    events: eventsCommand,
    series: seriesCommand,
    tags: tagsCommand,
    sports: sportsCommand,
    markets: marketsCommand,
  },
});
