// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/gamma/tags/related.js";

const args = {
  id: argument.string().required().describe("Tag ID or slug"),
} as const;

const options = {
  bySlug: option.boolean().short("s").describe("Lookup by slug instead of ID"),
  omitEmpty: option.boolean().describe("Omit empty related tags"),
  status: option.string().describe("Filter by status: active, closed, or all"),
} as const;

export const relatedCommand = defineCommand({
  name: "related",
  description: "List related tags for a given tag",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type RelatedArgs = InferArgs<typeof args>;
export type RelatedOptions = InferOptions<typeof options>;
