// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/data/users/activity.js";

const args = {
  user: argument.string().required().describe("User address"),
} as const;

const options = {
  sortDir: option.string().describe("Sort direction: ASC or DESC"),
  side: option.string().describe("Filter by side: BUY or SELL"),
  market: option.string().describe("Filter by comma-separated condition IDs"),
  start: option.number().describe("Start timestamp"),
  end: option.number().describe("End timestamp"),
  activityType: option
    .string()
    .describe(
      "Filter by activity types: TRADE, SPLIT, MERGE, REDEEM, REWARD, CONVERSION",
    ),
  eventId: option.string().describe("Filter by comma-separated event IDs"),
  limit: option.number().describe("Maximum number of results (default: 100)"),
  offset: option.number().describe("Pagination offset (default: 0)"),
  sortBy: option.string().describe("Sort field: TIMESTAMP, TOKENS, CASH"),
} as const;

export const activityCommand = defineCommand({
  name: "activity",
  description: "List on-chain activity for a user",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type ActivityArgs = InferArgs<typeof args>;
export type ActivityOptions = InferOptions<typeof options>;
