// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/data/users/closed-positions.js";

const args = {
  user: argument.string().required().describe("User address"),
} as const;

const options = {
  sortBy: option
    .string()
    .describe("Sort field: REALIZEDPNL, TITLE, PRICE, AVGPRICE, TIMESTAMP"),
  offset: option.number().describe("Pagination offset (default: 0)"),
  sortDir: option.string().describe("Sort direction: ASC or DESC"),
  limit: option.number().describe("Maximum number of results (default: 100)"),
  eventId: option.string().describe("Filter by comma-separated event IDs"),
  title: option.string().describe("Filter by title (max 100 chars)"),
  market: option.string().describe("Filter by comma-separated condition IDs"),
} as const;

export const closedPositionsCommand = defineCommand({
  name: "closed-positions",
  description: "List closed positions for a user",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type ClosedPositionsArgs = InferArgs<typeof args>;
export type ClosedPositionsOptions = InferOptions<typeof options>;
