// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/data/users/positions.js";

const args = {
  user: argument.string().required().describe("User address"),
} as const;

const options = {
  limit: option.number().describe("Maximum number of results (default: 100)"),
  market: option.string().describe("Filter by comma-separated condition IDs"),
  eventId: option.string().describe("Filter by comma-separated event IDs"),
  offset: option.number().describe("Pagination offset (default: 0)"),
  redeemable: option
    .boolean()
    .short("r")
    .describe("Filter redeemable positions"),
  sortBy: option
    .string()
    .describe(
      "Sort field: CURRENT, INITIAL, TOKENS, CASHPNL, PERCENTPNL, TITLE, PRICE, AVGPRICE",
    ),
  mergeable: option.boolean().short("m").describe("Filter mergeable positions"),
  sortDir: option.string().describe("Sort direction: ASC or DESC"),
} as const;

export const positionsCommand = defineCommand({
  name: "positions",
  description: "List current positions for a user",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type PositionsArgs = InferArgs<typeof args>;
export type PositionsOptions = InferOptions<typeof options>;
