// Generated by Bao - DO NOT EDIT

import { argument, defineCommand, type InferArgs } from "boune";
import { run } from "../../../handlers/data/users/traded-markets.js";

const args = {
  user: argument.string().required().describe("User address"),
} as const;

export const tradedMarketsCommand = defineCommand({
  name: "traded-markets",
  description: "Get total markets a user has traded",
  arguments: args,
  action: async ({ args }) => {
    await run(args);
  },
});

export type TradedMarketsArgs = InferArgs<typeof args>;
