// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/data/users/trades.js";

const options = {
  side: option.string().describe("Filter by side: BUY or SELL"),
  limit: option.number().describe("Maximum number of results (default: 100)"),
  eventId: option.string().describe("Filter by comma-separated event IDs"),
  takerOnly: option
    .boolean()
    .describe("Only include taker trades (default: true)"),
  user: option.string().short("u").describe("User address"),
  market: option.string().describe("Filter by comma-separated condition IDs"),
  offset: option.number().describe("Pagination offset (default: 0)"),
} as const;

export const tradesCommand = defineCommand({
  name: "trades",
  description: "List trades for a user or markets",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type TradesOptions = InferOptions<typeof options>;
