// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/data/users/values.js";

const args = {
  user: argument.string().required().describe("User address"),
} as const;

const options = {
  market: option.string().describe("Filter by comma-separated condition IDs"),
} as const;

export const valuesCommand = defineCommand({
  name: "values",
  description: "List total value of a user's positions",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type ValuesArgs = InferArgs<typeof args>;
export type ValuesOptions = InferOptions<typeof options>;
