// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/comments/list.js";

const options = {
  ascending: option.boolean().describe("Sort ascending"),
  offset: option.number().describe("Pagination offset"),
  entityType: option
    .string()
    .describe("Parent entity type: Event, Series, or market"),
  entityId: option.number().describe("Parent entity ID"),
  holdersOnly: option.boolean().describe("Restrict to position holders only"),
  getPositions: option.boolean().describe("Include position data"),
  limit: option.number().describe("Maximum number of results"),
  order: option.string().describe("Comma-separated list of fields to order by"),
} as const;

export const listCommand = defineCommand({
  name: "list",
  description: "List comments with filtering",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListOptions = InferOptions<typeof options>;
