// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/sports/list.js";

const options = {
  series: option.string().describe("Filter by series identifier"),
  sport: option.string().describe("Filter by sport identifier"),
  tag: option.string().describe("Filter by tag ID"),
} as const;

export const listCommand = defineCommand({
  name: "list",
  description: "List sports metadata",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListOptions = InferOptions<typeof options>;
