// Generated by Bao - DO NOT EDIT

import { argument, defineCommand, type InferArgs } from "boune";
import { run } from "../../../handlers/gamma/markets/get.js";

const args = {
  id: argument.string().required().describe("Market ID"),
} as const;

export const getCommand = defineCommand({
  name: "get",
  description: "Get a specific market by ID",
  arguments: args,
  action: async ({ args }) => {
    await run(args);
  },
});

export type GetArgs = InferArgs<typeof args>;
