// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/markets/list.js";

const options = {
  limit: option.number().describe("Maximum number of results (default: 10)"),
  closed: option.boolean().short("c").describe("Filter closed markets"),
  active: option.boolean().short("a").describe("Filter active markets"),
  offset: option.number().describe("Pagination offset (default: 0)"),
  archived: option.boolean().describe("Filter archived markets"),
} as const;

export const listCommand = defineCommand({
  name: "list",
  description: "List all markets with filtering",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListOptions = InferOptions<typeof options>;
