// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/markets/list-current.js";

const options = {
  limit: option.number().describe("Maximum number of results (default: 10)"),
  offset: option.number().describe("Pagination offset (default: 0)"),
} as const;

export const listCurrentCommand = defineCommand({
  name: "list-current",
  description: "List current markets (active, non-closed, non-archived)",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListCurrentOptions = InferOptions<typeof options>;
