// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/markets/list-clob.js";

const options = {
  offset: option.number().describe("Pagination offset"),
  limit: option.number().describe("Maximum number of results"),
} as const;

export const listClobCommand = defineCommand({
  name: "list-clob",
  description: "List CLOB-tradable markets (order book enabled)",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListClobOptions = InferOptions<typeof options>;
