// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { leaderboardCommand } from "./builders/leaderboard.js";
import { volumeCommand } from "./builders/volume.js";

export const buildersCommand = defineCommand({
  name: "builders",
  description: "Builder analytics commands",
  subcommands: {
    leaderboard: leaderboardCommand,
    volume: volumeCommand,
  },
});
