// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { listCommand } from "./holders/list.js";

export const holdersCommand = defineCommand({
  name: "holders",
  description: "Market holder commands",
  subcommands: {
    list: listCommand,
  },
});
