// Generated by Bao - DO NOT EDIT

import { argument, defineCommand, type InferArgs } from "boune";
import { run } from "../../handlers/data/live-volume.js";

const args = {
  eventId: argument.number().required().describe("Event ID"),
} as const;

export const liveVolumeCommand = defineCommand({
  name: "live-volume",
  description: "Get live volume for an event",
  arguments: args,
  action: async ({ args }) => {
    await run(args);
  },
});

export type LiveVolumeArgs = InferArgs<typeof args>;
