// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../handlers/data/open-interest.js";

const options = {
  market: option.string().describe("Filter by comma-separated condition IDs"),
} as const;

export const openInterestCommand = defineCommand({
  name: "open-interest",
  description: "Get market open interest",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type OpenInterestOptions = InferOptions<typeof options>;
