// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { activityCommand } from "./users/activity.js";
import { closedPositionsCommand } from "./users/closed-positions.js";
import { positionsCommand } from "./users/positions.js";
import { tradedMarketsCommand } from "./users/traded-markets.js";
import { tradesCommand } from "./users/trades.js";
import { valuesCommand } from "./users/values.js";

export const usersCommand = defineCommand({
  name: "users",
  description: "User data commands",
  subcommands: {
    activity: activityCommand,
    values: valuesCommand,
    trades: tradesCommand,
    closedPositions: closedPositionsCommand,
    positions: positionsCommand,
    tradedMarkets: tradedMarketsCommand,
  },
});
