// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { listCommand } from "./comments/list.js";

export const commentsCommand = defineCommand({
  name: "comments",
  description: "Comment commands",
  subcommands: {
    list: listCommand,
  },
});
