// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { getCommand } from "./events/get.js";
import { listCommand } from "./events/list.js";

export const eventsCommand = defineCommand({
  name: "events",
  description: "Event commands",
  subcommands: {
    list: listCommand,
    get: getCommand,
  },
});
