// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { getCommand } from "./markets/get.js";
import { listCommand } from "./markets/list.js";
import { listClobCommand } from "./markets/list-clob.js";
import { listCurrentCommand } from "./markets/list-current.js";

export const marketsCommand = defineCommand({
  name: "markets",
  description: "Market commands",
  subcommands: {
    listCurrent: listCurrentCommand,
    get: getCommand,
    listClob: listClobCommand,
    list: listCommand,
  },
});
