// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { getCommand } from "./series/get.js";
import { listCommand } from "./series/list.js";
import { listActiveCommand } from "./series/list-active.js";

export const seriesCommand = defineCommand({
  name: "series",
  description: "Series commands",
  subcommands: {
    get: getCommand,
    list: listCommand,
    listActive: listActiveCommand,
  },
});
