// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { listCommand } from "./sports/list.js";

export const sportsCommand = defineCommand({
  name: "sports",
  description: "Sports metadata commands",
  subcommands: {
    list: listCommand,
  },
});
