// Generated by Bao - DO NOT EDIT

import { defineCommand } from "boune";
import { getCommand } from "./tags/get.js";
import { listCommand } from "./tags/list.js";
import { relatedCommand } from "./tags/related.js";

export const tagsCommand = defineCommand({
  name: "tags",
  description: "Tag commands",
  subcommands: {
    list: listCommand,
    related: relatedCommand,
    get: getCommand,
  },
});
