// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/gamma/series/get.js";

const args = {
  id: argument.string().required().describe("Series ID"),
} as const;

const options = {
  includeChat: option.boolean().describe("Include chat data"),
} as const;

export const getCommand = defineCommand({
  name: "get",
  description: "Get a series by ID",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type GetArgs = InferArgs<typeof args>;
export type GetOptions = InferOptions<typeof options>;
