// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/series/list.js";

const options = {
  recurrence: option.string().describe("Filter by recurrence pattern"),
  ascending: option.boolean().describe("Sort ascending"),
  closed: option.boolean().describe("Filter by closed status"),
  order: option.string().describe("Comma-separated list of fields to order by"),
  slug: option.string().describe("Filter by series slug"),
  includeChat: option.boolean().describe("Include chat data"),
  limit: option.number().describe("Maximum number of results"),
  offset: option.number().describe("Pagination offset"),
  category: option.string().describe("Filter by category label"),
} as const;

export const listCommand = defineCommand({
  name: "list",
  description: "List series with filtering",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListOptions = InferOptions<typeof options>;
