// Generated by Bao - DO NOT EDIT

import { defineCommand, type InferOptions, option } from "boune";
import { run } from "../../../handlers/gamma/series/list-active.js";

const options = {
  limit: option.number().describe("Maximum number of results"),
  offset: option.number().describe("Pagination offset"),
} as const;

export const listActiveCommand = defineCommand({
  name: "list-active",
  description: "List active series (non-closed, non-archived)",
  options: options,
  action: async ({ options }) => {
    await run(options);
  },
});

export type ListActiveOptions = InferOptions<typeof options>;
