// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/data/holders/list.js";

const args = {
  market: argument
    .string()
    .required()
    .describe("Comma-separated condition IDs"),
} as const;

const options = {
  limit: option
    .number()
    .describe("Maximum number of results (default: 100, max: 500)"),
  minBalance: option.number().describe("Minimum balance filter (default: 0)"),
} as const;

export const listCommand = defineCommand({
  name: "list",
  description: "List top holders for markets",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type ListArgs = InferArgs<typeof args>;
export type ListOptions = InferOptions<typeof options>;
