// Generated by Bao - DO NOT EDIT
import { defineCli } from "boune";
import { dataCommand } from "./commands/data.js";
import { gammaCommand } from "./commands/gamma.js";

export const app = defineCli({
  name: "polys",
  version: "0.1.0",
  description: "CLI for Polymarket Data and Gamma APIs",
  commands: {
    gamma: gammaCommand,
    data: dataCommand,
  },
});
