// Generated by Bao - DO NOT EDIT

import {
  argument,
  defineCommand,
  type InferArgs,
  type InferOptions,
  option,
} from "boune";
import { run } from "../../../handlers/data/builders/leaderboard.js";

const args = {
  timePeriod: argument
    .string()
    .required()
    .describe("Time period: day, week, month, or all"),
} as const;

const options = {
  offset: option.number().describe("Pagination offset (default: 0)"),
  limit: option.number().describe("Maximum number of results (default: 25)"),
} as const;

export const leaderboardCommand = defineCommand({
  name: "leaderboard",
  description: "Get builder leaderboard",
  arguments: args,
  options: options,
  action: async ({ args, options }) => {
    await run(args, options);
  },
});

export type LeaderboardArgs = InferArgs<typeof args>;
export type LeaderboardOptions = InferOptions<typeof options>;
