// Generated by Bao - DO NOT EDIT

import { argument, defineCommand, type InferArgs } from "boune";
import { run } from "../../../handlers/data/builders/volume.js";

const args = {
  timePeriod: argument
    .string()
    .required()
    .describe("Time period: day, week, month, or all"),
} as const;

export const volumeCommand = defineCommand({
  name: "volume",
  description: "Get daily builder volume time-series",
  arguments: args,
  action: async ({ args }) => {
    await run(args);
  },
});

export type VolumeArgs = InferArgs<typeof args>;
